export const TAB_MENU = "snovy-tab-menu"
export const TAB_MENU_SECTION = "snovy-tab-menu-section"
export const TAB_MENU_ITEM = TAB_MENU + "-item"

export const COMBO_BOX = "snovy-combo-box"
export const COMBO_SPAWN = "snovy-combo-box-spawn"
export const DROPDOWN = "snovy-dropdown"
export const INPUT = "snovy-input"
export const COLOR_PICKER = "snovy-color-picker"
export const FORM = "snovy-form"
export const LABEL = "snovy-label"

export const LIST = "snovy-list"
export const LI = "snovy-list-item"
export const SIMPLE_LI = "li-simple-content"

export const I_ACTIVE = "active-item"
export const I_SELECT = "selected-item"
export const I_HIGHLIGHT = "highlighted-item"

export const STYLED_FOCUS = "styled-focus"
export const STYLED_HOVER = "styled-hover"
export const STYLED_HOVER_FILL = "styled-hover-fill"
export const WITH_BORDER = "with-border"
export const ABSOLUTE = "snovy-absolute"